continuando os testes

diff --git a/.github/workflows/deploy-lambda.yaml b/.github/workflows/deploy-lambda.yaml
--- a/.github/workflows/deploy-lambda.yaml
+++ b/.github/workflows/deploy-lambda.yaml
@@ -21,10 +21,15 @@ jobs:
         run: zip -r deployment-package.zip .
 
       - name: Debug
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
         run: |
           FUNCTION_NAME="postech-lambda-function"
+          ROLE_ARN="arn:aws:iam::180294201352:user/github-actions-lambda"
           echo "Testing if function exists..."
-          aws lambda get-function --function-name $FUNCTION_NAME --region "us-east-1" || echo "Function not found"
+          aws lambda get-function --function-name $FUNCTION_NAME --region "us-east-1" --role $ROLE_ARN || echo "Function not found"
           echo "Exiting script for debug."
           exit 0
 
