criei uma role "github-actions-lambda-role" para executar a função

diff --git a/.github/workflows/deploy-lambda.yaml b/.github/workflows/deploy-lambda.yaml
--- a/.github/workflows/deploy-lambda.yaml
+++ b/.github/workflows/deploy-lambda.yaml
@@ -20,16 +20,16 @@ jobs:
       - name: Prepare deployment package
         run: zip -r deployment-package.zip package.json src/services/authorizers/findByCPF.js
 
-      - name: Debug
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run: |
-          FUNCTION_NAME="postech-lambda-function"
-          echo "Testing if function exists..."
-          aws lambda get-function --function-name $FUNCTION_NAME --region "us-east-1" || echo "Function not found"
-          echo "Exiting script for debug."
-          exit 0
+      # - name: Debug
+      #   env:
+      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #   run: |
+      #     FUNCTION_NAME="postech-lambda-function"
+      #     echo "Testing if function exists..."
+      #     aws lambda get-function --function-name $FUNCTION_NAME --region "us-east-1" || echo "Function not found"
+      #     echo "Exiting script for debug."
+      #     exit 0
 
       - name: Validate deployment package
         run: |
@@ -46,7 +46,7 @@ jobs:
           FUNCTION_NAME="postech-lambda-function"
           REGION="us-east-1"
           ZIP_FILE="deployment-package.zip"
-          ROLE_ARN="arn:aws:iam::180294201352:user/github-actions-lambda"
+          ROLE_ARN="arn:aws:iam::180294201352:role/github-actions-lambda-role"
           HANDLER="src/services/authorizers/findByCPF.handler"
           RUNTIME="nodejs18.x"
 
